<?
/**
 * @desc Default layout for the entire module
 * @author Majisti
 */
?>
<?=$this->doctype() . PHP_EOL;?>
<html>
<head>
<?
print $this->headers();
?>
</head>
<body>
<div id="container">
    here2
    <!-- Header -->
    <div id="header">
        <div class="banner"></div>
    </div>

    <!-- Content -->
    <div id="content">
        <?=$this->layout()->content . PHP_EOL?>
    </div>
</div>
<?=$this->inlineScript();?>
</body>
</html>
